theme: minima
title: Te(ch)quity With Grace.
author: Stacey "Grace" Fenton
email: gracefenton3@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Information Technology Trainer, Software Developer, Speaker, and geek, I strive to bring forward my authentic self in written word. My hope is by sharing authentically, I can create a wedge big enough to spark ideas for equity and inclusion in IT.


# social links
twitter_username: staceymfenton
github_username:  gracefenton

show_excerpts: true # set to false to remove excerpts on the homepage
